### ISSUE TITLE
Hardware transcoding unavailable if /dev/dri owned by group 0 

### ISSUE THREAD

**Issue by poohcodez** [linuxserver/docker-plex#187]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

QNAP QTS 4.4.1.0949

This is my first time trying to get H/W transcoding working on QNAP, so I can't say if it worked before. 

A recent commit to /etc/cont-init.d/50-gid-video (256bf7a) disallows ownership by group 0. However, this update is in error because - when owned by group 0 - VIDEO_GID ends up null and the code fails in various ways depending on which path you take.

Additionally, there's no check if the assigned group has access to /dev/dri

For the case where there is no non-zero group with access to /dev/dri, the attached
changes ownership to the existing group video and assigns r/w privileges for /dev/dri -- I'll leave it here because I'm not sure if it breaks anything else for you:

[50-gid-video.diff.txt](https://github.com/linuxserver/docker-plex/files/3298446/50-gid-video.diff.txt)
[50-gid-video.txt](https://github.com/linuxserver/docker-plex/files/3298467/50-gid-video.txt)

**Comment by thelamer** [comment]
Yeah but we would never want to add our abc user to the "root" group or modify the root user's GID. 
At the core though why are your sys level video devices owned by root:root ? This is not default behavior on any Linux Distro.

**Comment by poohcodez** [comment]
Argh, yes indeed, why is that? The only answer I can give you is that QNAP/QTS seems to operate on a principle of least secure / most-open. I am but the messenger.

Note, that I didn't add abc to the "root" group, rather I assigned the video devices to the group video.

That notwithstanding, the existing code tries to disallow root/root but actually falls over instead.

But, I agree with you, it's a poor decision by QNAP.

**Comment by poohcodez** [comment]
Do you folks need anything more for me, or have further thoughts on what do with the issue?

**Comment by thelamer** [comment]
I mean the only thing we could do given the information provided is exit out of the script with no changes, but the end result is the same, the ABC user will not have access to the video accell device.

**Comment by poohcodez** [comment]
That's the beauty of open source, at least I can keep my change as a local mod. 

Changing it so it exists with a message of some kind, I think would be preferable to the slew of errors you now get when the script continues with a null variable.

For my information, am I missing something though? I updated 50-gid-video to give the abc group access to the device and I now get hardware transcoding. Is there some inherent issue in that approach that is going to bite me down the road? Your insight would be appreciated.

**Comment by ahiguero** [comment]
> That's the beauty of open source, at least I can keep my change as a local mod.
> 
> Changing it so it exists with a message of some kind, I think would be preferable to the slew of errors you now get when the script continues with a null variable.
> 
> For my information, am I missing something though? I updated 50-gid-video to allow access to the device through the video group and I now get hardware transcoding. Is there some inherent issue in that approach that is going to bite me down the road? Your insight would be appreciated.

i also have a qnap and i have tried to make this work on my nas. what exactly did you change inside the container to make this work?

**Comment by poohcodez** [comment]
@ahiguero > i also have a qnap and i have tried to make this work on my nas. what exactly did you change inside the container to make this work?

There are just a few steps to follow, this is maybe more detail than you needed but here it is for completeness.  What this does is to attach the direct rendering device _/dev/dri_ to the container, modify the group ownership to be _video_, make the _abc_ user a member of the video group, and assign r/w access to the device via the _video_ group. In practice, the only thing that changes from the current version is the assignment of group ownership and access. 

Using the existing docker-compose template as a guide:
1. Ensure the QNAP device supports hardware encoding (QNAP 451+, for example)
2. Modify the docker-compose file to:
    - Reference a Dockerfile
     - Attach /dev/dri via a device statement
3. Make a ./plex subdirectory:
    - Place the Dockerfile in the plex subdirectory
    - Place the 50-gid-video file in the plex subdirectory
    - You'll have to manually remove the .txt extension from the attachment
4. Create the container
    - **docker-compose up --build -d**
5. Enable h/w transcoding for plex
    - **Settings | Transcoder |  Use hardware acceleration when available**

docker-compose
```
---
version: "2"
services:
  plex:
    build:
      context:
        ./plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - </path/to/library>:/config
      - <path/to/tvseries>:/data/tvshows
      - </path/to/movies>:/data/movies
      - </path for transcoding>:/transcode
    devices:
       - /dev/dri:/dev/dri # For H/W transcoding
    restart: unless-stopped
```

Dockerfile
```
FROM linuxserver/plex
# Fix permisions on /dev/dri
COPY 50-gid-video /etc/cont-init.d/.
```
[50-gid-video.txt](https://github.com/linuxserver/docker-plex/files/3317052/50-gid-video.txt)

**Comment by thelamer** [comment]
fixed in #189

**Comment by ahiguero** [comment]
> @ahiguero > i also have a qnap and i have tried to make this work on my nas. what exactly did you change inside the container to make this work?
> 
> There are just a few steps to follow, this is maybe more detail than you needed but here it is for completeness. What this does is to attach the direct rendering device _/dev/dri_ to the container, modify the group ownership to be _video_, make the _abc_ user a member of the video group, and assign r/w access to the device via the _video_ group. In practice, the only thing that changes from the current version is the assignment of group ownership and access.
> 
> Using the existing docker-compose template as a guide:
> 
> 1. Ensure the QNAP device supports hardware encoding (QNAP 451+, for example)
> 2. Modify the docker-compose file to:
>    
>    * Reference a Dockerfile
>    * Attach /dev/dri via a device statement
> 3. Make a ./plex subdirectory:
>    
>    * Place the Dockerfile in the plex subdirectory
>    * Place the 50-gid-video file in the plex subdirectory
>    * You'll have to manually remove the .txt extension from the attachment
> 4. Create the container
>    
>    * **docker-compose up --build -d**
> 5. Enable h/w transcoding for plex
>    
>    * **Settings | Transcoder |  Use hardware acceleration when available**
> 
> docker-compose
> 
> ```
> ---
> version: "2"
> services:
>   plex:
>     build:
>       context:
>         ./plex
>     container_name: plex
>     network_mode: host
>     environment:
>       - PUID=1000
>       - PGID=1000
>       - VERSION=docker
>     volumes:
>       - </path/to/library>:/config
>       - <path/to/tvseries>:/data/tvshows
>       - </path/to/movies>:/data/movies
>       - </path for transcoding>:/transcode
>     devices:
>        - /dev/dri:/dev/dri # For H/W transcoding
>     restart: unless-stopped
> ```
> 
> Dockerfile
> 
> ```
> FROM linuxserver/plex
> # Fix permisions on /dev/dri
> COPY 50-gid-video /etc/cont-init.d/.
> ```
> 
> [50-gid-video.txt](https://github.com/linuxserver/docker-plex/files/3317052/50-gid-video.txt)

thanks for the detialed explanation. my qnap is a TVS-951X  and i downlaoded the lastest image which is suposed to fix this error but i still see that HW is not working

i get the following error in the logs

[FFMPEG] - No VA display found for device: /dev/dri/renderD128.

**Comment by poohcodez** [comment]
Unfortunately, the latest fix forgets to set group permissions on the direct rendering device, so user abc still doesn't have access. It's hard for the linuxserver crew as they likely don't have a QNAP device to test with.
 
At line 9 in the updated 50-gid-video you need to add:  **chmod -R ug+rwX /dev/dri**

See my previous comments/attachment for more details

**Comment by thelamer** [comment]
I tested this by chowning my own video devices. 
Are you saying that Qnap does not even allow group root access to these devices ? 

There is no world where we would be modifying the permissions of system level devices from the container.

**Comment by thelamer** [comment]
Also side note @poohcodez you need to file this upstream. They are doing something no one else does and it is effecting one of the most popularly consumed applications for their devices. 

You should not be band aid fixing this stuff and what I would assume is other users are just doing stuff like `chmod -R 777` . 

Ping them about this https://helpdesk.qnap.com/index.php?

**Comment by CHBMB** [comment]
What I've traditionally done on Unraid is `chown -R nobody:users /dev/dri` at system startup (nobody:users being the default Unraid user) Is that not possible with QNAP

**Comment by poohcodez** [comment]
@thelamer If you know of a way to get past the helpdesk to someone who actually does something, I'd love to know the secret. Even when you go to them with pointers as to where in their code their problems are, it's a pointless exercise that ends in frustration. That doesn't mean you should fix their errors, but it's not something they would accept as an error. If you have contacts, please do share them.

In terms of Plex on QNAP. They have their own Plex package that runs as admin (root) and is invariably out of date. H/W transcoding works under their package. However, if you want up-to-date Plex then it's a container or a VM.  Most QNAP applications run as the root user. Ghastly doesn't even come close to describing it.

@CHBMB Yes, you are absolutely right. I already do that to fix a bunch of other QNAP silliness. That approach most certainly works on QTS for Plex too. I was trying to help out here but we all have more pressing things to attend to then debate how QTS is broken by design.

Just for anyone following along at home: QNAP has some limited autorun support found (at least for me) at **/share/CACHEDEV1_DATA/.system/autorun/** - You enable it from Control Panel | Hardware | Run user defined process during startup

**Comment by ahiguero** [comment]
Wrong statement there as Plex offers a package that you can install on the NAS (QNAP) QBNAP just stopped building the package themselves a while back

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by CHBMB** [comment]
@ahiguero What?

**Comment by ahiguero** [comment]
QNAP stopped supplying the the plex app a while back as it is supplied by plex directly. That’s the reason why QNAP stopped maintaining it, and the reason why the QnAP plex app is so outdated

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
