### ISSUE TITLE
Plex not starting (symbol not found)

### ISSUE THREAD

**Issue by lordchristiano** [linuxserver/docker-plex#335]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

 Plex will not start

Error relocating /usr/lib/plexmediaserver/Plex Media Server: drmGetDevices2: symbol not found
                                                                                                 Starting Plex Media Server.
                  Error relocating /usr/lib/plexmediaserver/Plex Media Server: drmGetDevices2: symbol not found
     Starting Plex Media Server.
                                Error relocating /usr/lib/plexmediaserver/Plex Media Server: drmGetDevices2: symbol not found
                   Starting Plex Media Server.

------------------------------

## Expected Behavior
 Plex container starting

## Current Behavior
 not starting

## Steps to Reproduce

1. start containr
2.
3.
4.

## Environment
**OS:** QNAP
**CPU architecture:** x86_64/arm32/arm64 x64
**How docker service was installed:**
 qnap container (command line)

## Docker logs

  Setting up plexmediaserver (1.29.1.6260-420892357) ...
                                                                         PlexMediaServer install: Docker detected. Postinstallation tasks not required. Continuing.
                                                         cont-init: info: /etc/cont-init.d/60-plex-update exited 0
        cont-init: info: running /etc/cont-init.d/99-custom-files
                                                                 [custom-init] No custom files found, skipping...
       cont-init: info: /etc/cont-init.d/99-custom-files exited 0
                                                                 s6-rc: info: service legacy-cont-init successfully started
                 s6-rc: info: service init-mods: starting
                                                         s6-rc: info: service init-mods successfully started
  s6-rc: info: service init-mods-package-install: starting
                                                          s6-rc: info: service init-mods-package-install successfully started
                   s6-rc: info: service init-mods-end: starting
                                                               s6-rc: info: service init-mods-end successfully started
            s6-rc: info: service init-services: starting
                                                        s6-rc: info: service init-services successfully started
     s6-rc: info: service legacy-services: starting
                                                   services-up: info: copying legacy longrun plex (no readiness notification)
                   s6-rc: info: service legacy-services successfully started
                                                                            s6-rc: info: service 99-ci-service-check: starting
                    Starting Plex Media Server.
                                               [ls.io-init] done.
                                                                 s6-rc: info: service 99-ci-service-check successfully started
                    Error relocating /usr/lib/plexmediaserver/Plex Media Server: drmGetDevices2: symbol not found
       Starting Plex Media Server.
                                  Error relocating /usr/lib/plexmediaserver/Plex Media Server: drmGetDevices2: symbol not found
                     Starting Plex Media Server.
                                                Error relocating /usr/lib/plexmediaserver/Plex Media Server: drmGetDevices2: symbol not found
                                   Starting Plex Media Server.
                                                              Error relocating /usr/lib/plexmediaserver/Plex Media Server: drmGetDevices2: symbol not found
                                                 Starting Plex Media Server.
                                                                            Error relocating /usr/lib/plexmediaserver/Plex Media Server: drmGetDevices2: symbol not found
                                                               Starting Plex Media Server.
                                                                                          Error relocating /usr/lib/plexmediaserver/Plex Media Server: drmGetDevices2: symbol not found
                                                                             Starting Plex Media Server.
                                                                                                        Error relocating /usr/lib/plexmediaserver/Plex Media Server: drmGetDevices2: symbol not found
                                                                                           Starting Plex Media Server.
            Error relocating /usr/lib/plexmediaserver/Plex Media Server: drmGetDevices2: symbol not found

**Comment by jsetton** [comment]
This is related to an outdated library part of the current NVIDIA drivers package on QNAP NAS.

Adding `/usr/lib/plexmediaserver/lib` at the beginning of the `LD_LIBRARY_PATH ` environment variable docker setting should resolve it.

https://forums.plex.tv/t/error-on-start-plexmediaserver-1-29-1-6260-420892357-drmgetdevices2/812910/43

**Comment by lordchristiano** [comment]
Thanks for this, hardware accel thru nvidia still not working BUT it is no longer crashing at boot.

**Comment by lordchristiano** [comment]
@jsetton were you able to get hardware acceleration working with the new image?

**Comment by jsetton** [comment]
@lordchristiano it is working fine. You may want to post on the Plex forum post I linked above including your Docker Compose template and close this issue since this is just a configuration issue related to the QNAP environment.

**Comment by lordchristiano** [comment]
Thanks, I dont use docker compose unfortunately

**Comment by jsetton** [comment]
> I dont use docker compose unfortunately

You can also include your Docker run command arguments.
